version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Currently, we can't rely on using the Gradle Daemon due to a bug in Loom.
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run:
        name: Fetching dependencies
        command: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Building and remapping jars
        command: gradle remapJar remapSourcesJar

    - run:
        name: Running tests
        command: gradle check

    - store_artifacts:
        path: ~/repo/libs
        destination: jars